"""Auth module - users, refresh_tokens, security_audit_log

Revision ID: b8e8b602f791
Revises: ef8d04f76c39
Create Date: 2026-04-03 11:55:59.698546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e8b602f791'
down_revision = 'ef8d04f76c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_user', ['user_id'], unique=False)

    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_google', ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_google')

    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_created')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_tokens_user')

    # ### end Alembic commands ###
